{
    "name": "record_replay.InvocationException",
    "extends": [],
    "memberOf": "record_replay",
    "events": [],
    "methods": [
        {
            "name": "InvocationException",
            "type": "",
            "desc": "",
            "static": false,
            "memberOf": "record_replay.InvocationException",
            "sig": "",
            "params": [],
            "isConstructor": true,
            "href": "package-file_record_replay\/InvocationException\/InvocationException.html",
            "example": "",
            "isDeprecated": false
        }
    ],
    "props": [],
    "isMixin": false,
    "isEnum": false,
    "isTypedef": false,
    "isConstant": false,
    "isAbstract": false,
    "implementors": [],
    "realImplementors": [],
    "cn": [],
    "href": "package-file_record_replay\/InvocationException-class.html",
    "desc": "<p>Exception thrown during replay when an invocation recorded error, but we\nwere unable to find a type-specific converter to deserialize the recorded\nerror into a more specific exception type.<\/p>\n    ",
    "example": "",
    "isDeprecated": false,
    "dtype": "class",
    "shortname": "InvocationException"
}